# Generated by Django 4.2.30 on 2026-07-22 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBuyCryptoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agentName', models.CharField(max_length=100)),
                ('agentemail', models.EmailField(max_length=254)),
                ('currencyname', models.CharField(max_length=100)),
                ('currentprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('payableammount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AgentBuyedTransactions',
            },
        ),
        migrations.CreateModel(
            name='BitAgentRegisterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pswd', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('cryptcurrency', models.CharField(max_length=100)),
                ('status', models.CharField(default='waiting', max_length=50)),
                ('authkey', models.CharField(default='waiting', max_length=100)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'agentregister',
            },
        ),
        migrations.CreateModel(
            name='BitUserRegisterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pswd', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='waiting', max_length=50)),
                ('authkey', models.CharField(default='waiting', max_length=100)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'userregister',
            },
        ),
        migrations.CreateModel(
            name='BlockChainLedger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customeremail', models.EmailField(max_length=254)),
                ('agentemail', models.EmailField(max_length=254)),
                ('currencyname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('paidammout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('blockchainmoney', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'BlockChainLedger',
            },
        ),
        migrations.CreateModel(
            name='CryptCurrencyRateModel',
            fields=[
                ('currencytype', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doller', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rupee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('originalprice', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'currencyrate',
            },
        ),
        migrations.CreateModel(
            name='CurrencyUpdateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currencyname', models.CharField(max_length=100)),
                ('conversionRate', models.FloatField()),
                ('newCurrencyValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('originalCurrencyValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chnageValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profitorloss', models.CharField(max_length=50)),
                ('changedate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'currencychnagetable',
            },
        ),
        migrations.CreateModel(
            name='UserBuyingCryptoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('currencyname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('agentemail', models.EmailField(max_length=254)),
                ('singlecoingamount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payableammount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserBuyingCryptoModel',
            },
        ),
        migrations.CreateModel(
            name='CustomerHadCoins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currencyName', models.CharField(max_length=100)),
                ('customeremail', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'CustomerContainCoins',
                'unique_together': {('currencyName', 'customeremail')},
            },
        ),
        migrations.CreateModel(
            name='AgentHadCrypto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currencyName', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'agentscryptoquantity',
                'unique_together': {('currencyName', 'useremail')},
            },
        ),
    ]
